//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mgr21ProcKiller.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mgr21ProcKiller.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Items.
        /// </summary>
        internal static string AddItemsView_ButtonAddItems {
            get {
                return ResourceManager.GetString("AddItemsView_ButtonAddItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main menu.
        /// </summary>
        internal static string AddItemsView_ButtonBack_Tooltip {
            get {
                return ResourceManager.GetString("AddItemsView_ButtonBack_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string AddItemsView_ButtonBrowse_Content {
            get {
                return ResourceManager.GetString("AddItemsView_ButtonBrowse_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string AddItemsView_ButtonRemove_Content {
            get {
                return ResourceManager.GetString("AddItemsView_ButtonRemove_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Location.
        /// </summary>
        internal static string AddItemsView_DataGrid_Header1 {
            get {
                return ResourceManager.GetString("AddItemsView_DataGrid_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Duplicate items won&apos;t be added.
        /// </summary>
        internal static string AddItemsView_TextBlockNote_Text {
            get {
                return ResourceManager.GetString("AddItemsView_TextBlockNote_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Items To Black List.
        /// </summary>
        internal static string AddItemsView_TextBlockTitle_Text {
            get {
                return ResourceManager.GetString("AddItemsView_TextBlockTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding items to black list....
        /// </summary>
        internal static string AddItemsVm_Code1 {
            get {
                return ResourceManager.GetString("AddItemsVm_Code1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items added to black list. Refreshing service....
        /// </summary>
        internal static string AddItemsVm_Code2 {
            get {
                return ResourceManager.GetString("AddItemsVm_Code2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service refreshed. Operation completed successfully.
        /// </summary>
        internal static string AddItemsVm_Code3 {
            get {
                return ResourceManager.GetString("AddItemsVm_Code3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items being added. Check black list again for duplicate items.
        /// </summary>
        internal static string AddItemsVm_Code4 {
            get {
                return ResourceManager.GetString("AddItemsVm_Code4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while retrieving data from source. Adding items failed.
        /// </summary>
        internal static string AddItemsVm_Code5 {
            get {
                return ResourceManager.GetString("AddItemsVm_Code5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Items.
        /// </summary>
        internal static string BlackListView_ButtonAddItems_Content {
            get {
                return ResourceManager.GetString("BlackListView_ButtonAddItems_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string BlackListView_ButtonClear_Content {
            get {
                return ResourceManager.GetString("BlackListView_ButtonClear_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Process Killer &amp;amp; Black List.
        /// </summary>
        internal static string BlackListView_ButtonReload_ToolTip {
            get {
                return ResourceManager.GetString("BlackListView_ButtonReload_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string BlackListView_ButtonRemove_Content {
            get {
                return ResourceManager.GetString("BlackListView_ButtonRemove_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        internal static string BlackListView_DataGrid_Header1 {
            get {
                return ResourceManager.GetString("BlackListView_DataGrid_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Location.
        /// </summary>
        internal static string BlackListView_DataGrid_Header2 {
            get {
                return ResourceManager.GetString("BlackListView_DataGrid_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (bytes).
        /// </summary>
        internal static string BlackListView_DataGrid_Header3 {
            get {
                return ResourceManager.GetString("BlackListView_DataGrid_Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string BlackListVm_Code1 {
            get {
                return ResourceManager.GetString("BlackListVm_Code1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Refreshed. Operation completed successfully.
        /// </summary>
        internal static string BlackListVm_Code10 {
            get {
                return ResourceManager.GetString("BlackListVm_Code10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove item, please Reload and try again.
        /// </summary>
        internal static string BlackListVm_Code11 {
            get {
                return ResourceManager.GetString("BlackListVm_Code11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data loaded successfully.
        /// </summary>
        internal static string BlackListVm_Code2 {
            get {
                return ResourceManager.GetString("BlackListVm_Code2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load data. Please close application and open again.
        /// </summary>
        internal static string BlackListVm_Code3 {
            get {
                return ResourceManager.GetString("BlackListVm_Code3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing black list....
        /// </summary>
        internal static string BlackListVm_Code4 {
            get {
                return ResourceManager.GetString("BlackListVm_Code4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black list is empty. Refreshing service....
        /// </summary>
        internal static string BlackListVm_Code5 {
            get {
                return ResourceManager.GetString("BlackListVm_Code5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Refreshed. Operation completed successfully.
        /// </summary>
        internal static string BlackListVm_Code6 {
            get {
                return ResourceManager.GetString("BlackListVm_Code6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to clear black list. Please Reload and try again.
        /// </summary>
        internal static string BlackListVm_Code7 {
            get {
                return ResourceManager.GetString("BlackListVm_Code7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing item....
        /// </summary>
        internal static string BlackListVm_Code8 {
            get {
                return ResourceManager.GetString("BlackListVm_Code8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item successfully removed. Refreshing service....
        /// </summary>
        internal static string BlackListVm_Code9 {
            get {
                return ResourceManager.GetString("BlackListVm_Code9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MainWindow_CmdBar_About {
            get {
                return ResourceManager.GetString("MainWindow_CmdBar_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainWindow_CmdBar_Settings {
            get {
                return ResourceManager.GetString("MainWindow_CmdBar_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string SettingsView_ButtonExit_Content {
            get {
                return ResourceManager.GetString("SettingsView_ButtonExit_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string SettingsView_ButtonUpdate_Content {
            get {
                return ResourceManager.GetString("SettingsView_ButtonUpdate_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings updated.
        /// </summary>
        internal static string SettingsView_CodeBehind_Code1 {
            get {
                return ResourceManager.GetString("SettingsView_CodeBehind_Code1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings updated with error during service restart.
        /// </summary>
        internal static string SettingsView_CodeBehind_Code2 {
            get {
                return ResourceManager.GetString("SettingsView_CodeBehind_Code2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete all fields.
        /// </summary>
        internal static string SettingsView_CodeBehind_Code3 {
            get {
                return ResourceManager.GetString("SettingsView_CodeBehind_Code3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both password lengths must be greater than 5 chars.
        /// </summary>
        internal static string SettingsView_CodeBehind_Code4 {
            get {
                return ResourceManager.GetString("SettingsView_CodeBehind_Code4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password cannot be the same with old password.
        /// </summary>
        internal static string SettingsView_CodeBehind_Code5 {
            get {
                return ResourceManager.GetString("SettingsView_CodeBehind_Code5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master key file is not found.
        /// </summary>
        internal static string SettingsView_CodeBehind_Code6 {
            get {
                return ResourceManager.GetString("SettingsView_CodeBehind_Code6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        internal static string SettingsView_CodeBehind_Code7 {
            get {
                return ResourceManager.GetString("SettingsView_CodeBehind_Code7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is invalid.
        /// </summary>
        internal static string SettingsView_CodeBehind_Code8 {
            get {
                return ResourceManager.GetString("SettingsView_CodeBehind_Code8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string SettingsView_CodeBehind_Error {
            get {
                return ResourceManager.GetString("SettingsView_CodeBehind_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SettingsView_CodeBehind_Success {
            get {
                return ResourceManager.GetString("SettingsView_CodeBehind_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior Settings.
        /// </summary>
        internal static string SettingsView_GroupBoxBehavior_Header {
            get {
                return ResourceManager.GetString("SettingsView_GroupBoxBehavior_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Master Password.
        /// </summary>
        internal static string SettingsView_GroupBoxPassword_Header {
            get {
                return ResourceManager.GetString("SettingsView_GroupBoxPassword_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Interval: .
        /// </summary>
        internal static string SettingsView_RunInterval_Text {
            get {
                return ResourceManager.GetString("SettingsView_RunInterval_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (milliseconds).
        /// </summary>
        internal static string SettingsView_RunMs_Text {
            get {
                return ResourceManager.GetString("SettingsView_RunMs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison Type: .
        /// </summary>
        internal static string SettingsView_TextBlockComparison_Text {
            get {
                return ResourceManager.GetString("SettingsView_TextBlockComparison_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password: .
        /// </summary>
        internal static string SettingsView_TextBlockCurrentPwd_Text {
            get {
                return ResourceManager.GetString("SettingsView_TextBlockCurrentPwd_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password: .
        /// </summary>
        internal static string SettingsView_TextBlockNewPwd_Text {
            get {
                return ResourceManager.GetString("SettingsView_TextBlockNewPwd_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string StartupView_ButtonExit_Content {
            get {
                return ResourceManager.GetString("StartupView_ButtonExit_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string StartupView_ButtonLogin_Content {
            get {
                return ResourceManager.GetString("StartupView_ButtonLogin_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        internal static string StartupView_ButtonSetPassword_Content {
            get {
                return ResourceManager.GetString("StartupView_ButtonSetPassword_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete all fields.
        /// </summary>
        internal static string StartupView_CodeBehind_Code1 {
            get {
                return ResourceManager.GetString("StartupView_CodeBehind_Code1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        internal static string StartupView_CodeBehind_Code2 {
            get {
                return ResourceManager.GetString("StartupView_CodeBehind_Code2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master password has been set.
        /// </summary>
        internal static string StartupView_CodeBehind_Code3 {
            get {
                return ResourceManager.GetString("StartupView_CodeBehind_Code3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete password field.
        /// </summary>
        internal static string StartupView_CodeBehind_Code4 {
            get {
                return ResourceManager.GetString("StartupView_CodeBehind_Code4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string StartupView_CodeBehind_Error {
            get {
                return ResourceManager.GetString("StartupView_CodeBehind_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string StartupView_CodeBehind_Success {
            get {
                return ResourceManager.GetString("StartupView_CodeBehind_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input password.
        /// </summary>
        internal static string StartupView_PwdBox_Watermark {
            get {
                return ResourceManager.GetString("StartupView_PwdBox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string StartupView_PwdBoxConfirm_Watermark {
            get {
                return ResourceManager.GetString("StartupView_PwdBoxConfirm_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input new password.
        /// </summary>
        internal static string StartupView_PwdBoxNew_Watermark {
            get {
                return ResourceManager.GetString("StartupView_PwdBoxNew_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string StartupView_RunLogin_Text {
            get {
                return ResourceManager.GetString("StartupView_RunLogin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Master Password.
        /// </summary>
        internal static string StartupView_TextBlockMasterPassword_Text {
            get {
                return ResourceManager.GetString("StartupView_TextBlockMasterPassword_Text", resourceCulture);
            }
        }
    }
}
